name: neural_tree
description: Fast Artificial Neural Network Library (Based on SIMD and GPU computations)
version: 1.0.5
repository: https://github.com/gnudles/neural_tree

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
   path: ^1.8.0
   opencl: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

